* 中文相关
** 退出insert模式时，自动切成英文输入法。 貌似只有pyim输入法才有效
*** step1： 在dotspacemacs-configuration-layers 中配置并启用 chinese
	#+begin_src elisp
	(chinese :variables
			  chinese-enable-fcitx t)
	#+end_src


*** setp2 在dotspacemacs/user-config() 配置词库
	#+begin_src elisp
	;; 给pyim添加词库。没有词库的pyim是及其不好用的。
	(setq pyim-dicts
		   '((:name "bigdict" :file "/Users/monty/DIGEST/SOFT/Emacs/pyim_dict/pyim-bigdict.pyim")))
	 ;; 选词框显示8个候选词
	(setq pyim-page-length 8)
	#+end_src




**  解决org-table中英混排对齐问题
*** 方法一:  Ubuntu Mono的中文字体宽度是英文字体宽度2倍的字体
**** 安装字体
	 Ubuntu Mono: https://design.ubuntu.com/font/    Ubuntu Mono的中文字体宽度是英文字体宽度2倍的字体
	 Source Code Pro:  https://github.com/adobe-fonts/source-code-pro
**** 设置默认字体
	 dotspacemacs-default-font '("Source Code Pro"
	 :size 14
	 :weight normal
	 :width normal
	 :powerline-scale 1.1)
**** 在(defun dotspacemacs/user-config () 中单独设置 org-table 的中文字体
	 (custom-set-faces
	 '(org-table ((t (:foreground "#6c71c4" :family "Ubuntu Mono")))))

*** 方法二： 根据默认字体的大小，找到一个初始宽度为默认字体宽度２倍的中文字体
	# 设定一个中文字体相对默认字体的放缩比例，比如英文字体是 Meslo LG M :size 14 ，
	# 中文字体 Noto Sans Mono CJK SC 放缩比例1.2正合适。这种方法的缺点是，字体不好找。
**** 安装字体
	 Meslo LG M  : https://github.com/andreberg/Meslo-Font

	 Noto Sans Mono CJK SC : https://www.google.com/get/noto/  下载这个 Noto Sans CJK SC

**** 设置默认字体
	 dotspacemacs-default-font '("Meslo LG M"
	 :size 14
	 :weight normal
	 :width normal
	 :powerline-scale 1.1)


**** 在(defun dotspacemacs/user-config () 设置默认字体宽度２倍的中文字体
	 # ;;当遇到 kana han symbol cjk-misc bopomofo 字符集时，Emacs 明白需要使用
	 # ;; Noto Sans Mono CJK SC 字体，同时设置缩放比例
	 (dolist (charset '(kana han symbol cjk-misc bopomofo))
	 (set-fontset-font (frame-parameter nil 'font)
	 charset (font-spec :family "Noto Sans Mono CJK SC"))
	 (setq face-font-rescale-alist '(("Noto Sans Mono CJK SC" . 1.2))))


* UI 设置

** 启用 monokai 配色
*** step1: 在dotspacemacs-configuration-layers 启用 themes-megapack


*** step2: 在(custom-set-variables 设置 monokai 高亮选中文本的颜色
	'(monokai-highlight "#8B4513")


** 直接修改值
*** 让 learder key  SPC 响应快一点。
	dotspacemacs-which-key-delay 0.1



*** 编辑风格选择 hybrid
	dotspacemacs-editing-style 'hybrid

** dotspacemacs-configuration-layers
*** 在 Mac 电脑上添加 osx， 这样会自动做一些 Mac 有关的设置。
	osx



** (defun dotspacemacs/user-init ()
*** 使用国内的源
	(setq configuration-layer--elpa-archives
	'(
	("melpa-cn" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
	("org-cn"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/org/")
	("gnu-cn"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
	)
	)

** dotspacemacs/user-config()
*** 光标居中
	(global-centered-cursor-mode)

*** 取消中英混排时多出的空格。
	(global-pangu-spacing-mode 0)
	(set (make-local-variable 'pangu-spacing-real-insert-separtor) nil)

*** 在底部 mode-line 显示当前buffer的完整路径
	(with-eval-after-load 'spaceline-config
	(spaceline-define-segment buffer-id
	(if (buffer-file-name)
	(abbreviate-file-name (buffer-file-name))
	(powerline-buffer-id))))

*** 设置 org 任务层级 对应的图标, 这里只设置了4级。 要个多级，继续往后加就是了。
	(with-eval-after-load 'org
	(setq org-bullets-bullet-list '("☰" "☷" "☯" "☭"))
	)

*** c_c++ 缩进4个空格
	#+begin_src elisp
  (setq-default c-basic-offset 4
				tab-width 4
				indent-tabs-mode t)
  (setq c-default-style "linux")
	#+end_src

*** Mac下让emacs和 系统剪切板 共享的方法 https://github.com/syl20bnr/spacemacs/issues/10896
	# 1. 添加附加包 dotspacemacs-additional-packages '(osx-clipboard)
	# 2. 在user-config() 下添加如下配置
	#+begin_src elisp
 (use-package osx-clipboard
   :commands
   (osx-clipboard-paste-function osx-clipboard-cut-function))

 (defun aj/select-text (text &rest ignore)
   (if (display-graphic-p)
	   (gui-select-text text)
	 (osx-clipboard-cut-function text)))

 (defun aj/selection-value ()
   (if (display-graphic-p)
	   (gui-selection-value)
	 (osx-clipboard-paste-function)))

 (setq interprogram-cut-function 'aj/select-text
	   interprogram-paste-function 'aj/selection-value)

 (provide 'init-macos-terminal-copy-paste)
	#+end_src

* Git 设置
** 在dotspacemacs-configuration-layers 启用 git 和 version-control
** 在defun dotspacemacs/user-init ()中设置
   (setq-default git-magit-status-fullscreen t)

* Test table align
  |------------------+----------------+------------------------|
  | tesr看看不错     | 环澳           | very good              |
  |------------------+----------------+------------------------|
  | this is good job | your are right | thank you 妈妈         |
  | fdjfie           | jda            | 这回，卡款ikdai1 ,dai1 |
